name: Static Checks
run-name: ${{ github.actor }} is pushing a new commit
on: [ push ]
jobs:
  pull-and-install-deps:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Checkout code to branch ${{ github.ref }}."
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Installing the node engine.
        uses: actions/setup-node@v4
        with:
          node-version: '20.17.0'

      - name: Install deps
        run: yarn

      - name: Check Prettier format
        run: yarn run format -c

      - name: Check ESLint
        run: yarn run eslint "{src,apps,libs,test}/**/*.ts" --fix-dry-run

      - run: echo "Job status ${{ job.status }}."

      - name: Prepare .env for testing
        run: |
          echo ${{ secrets.TEST_ENV_CONTENT }} >> $GITHUB_ENV; echo ${{ secrets.TEST_ENV_CONTENT }} >> ${{ github.workspace }}/.env
      
      - name: Export .env vars
        run: |
          export;

      - name: Run Unit Test
        run: yarn  run test

      - name: Run E2E Test
        run: yarn run test:e2e

      - run: echo "Job status ${{ job.status }}."

      - run: echo "🚧 build source code on branch ${{ github.ref }}."

      - name: Run build project
        run: yarn run build

      - run: echo "Job status ${{ job.status }}."
